// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_38f1049a72ecb554aa7e8945dd60b8b0_5bd1a86825474c208c5bad06840e009f : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_38f1049a72ecb554aa7e8945dd60b8b0_10370f48584b4f9ea10190042d23e103 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 1;
        public override int FieldIndex => 0;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetQuaternion().ToUnityQuaternion();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetQuaternion(Value.ToCoreQuaternion());
            }
            else
            {
                field.SetQuaternion(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToCoreQuaternion());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_38f1049a72ecb554aa7e8945dd60b8b0_3de2a11c92b043b6a668faba0a1c2b1b : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 17;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_38f1049a72ecb554aa7e8945dd60b8b0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_38f1049a72ecb554aa7e8945dd60b8b0>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["5bd1a86825474c208c5bad06840e009f"] = new Binding_38f1049a72ecb554aa7e8945dd60b8b0_5bd1a86825474c208c5bad06840e009f(),
			["10370f48584b4f9ea10190042d23e103"] = new Binding_38f1049a72ecb554aa7e8945dd60b8b0_10370f48584b4f9ea10190042d23e103(),
			["3de2a11c92b043b6a668faba0a1c2b1b"] = new Binding_38f1049a72ecb554aa7e8945dd60b8b0_3de2a11c92b043b6a668faba0a1c2b1b(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_38f1049a72ecb554aa7e8945dd60b8b0()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_38f1049a72ecb554aa7e8945dd60b8b0 Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_38f1049a72ecb554aa7e8945dd60b8b0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
